# Generated by Django 4.2.16 on 2024-11-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='任务标题')),
                ('description', models.TextField(blank=True, verbose_name='任务内容')),
                ('status', models.CharField(choices=[('pending', '未完成'), ('completed', '已完成')], default='pending', max_length=10, verbose_name='任务状态')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=10, verbose_name='任务优先级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
        ),
    ]
